---
# Main list of tasks to be executed.
#
#   Fail the play if it runs on an unsupported platform.
- name: Assert platform is supported
  tags: tomcat
  assert:
    that:
      - ansible_os_family in tomcat_supported_platforms
      - ansible_distribution in tomcat_supported_distributions


- name: Include --check mode detection
  tags: tomcat
  include: "{{ tomcat_path_to_lib_role }}/silpion.lib/tasks/checkmodedetection.yml"

- name: Detect --check mode on initial run
  tags: tomcat
  set_fact:
    tomcat_fact_is_not_initial_check_mode: "{{ true if ((ansible_local|default({})).tomcat is defined or not lib_fact_check_mode) else false }}"


- name: Include version specific configuration
  tags: tomcat
  include: "{{ tomcat_path_to_lib_role }}/silpion.lib/tasks/version-specific-vars.yml"
  vars:
    version: "{{ tomcat_version }}"

- name: Assert version specific configuration
  tags: tomcat
  assert:
    that:
      - tomcat_redis_checksum not in (None, "")

- name: Detect version upgrade
  tags: tomcat
  when:
    - ansible_local.tomcat.general.version is defined
    - ansible_local.tomcat.general.version != tomcat_version
  set_fact:
    tomcat_fact_upgrade_installation: true

- name: Ensure upgrade policies
  tags: tomcat
  when:
    - not tomcat_service_allow_restart|bool
    - tomcat_fact_upgrade_installation is defined and tomcat_fact_upgrade_installation
  fail:
    msg: "Product version upgrade detected, but service management is prohibited"

# Manage system services
- name: Configure service management
  tags: tomcat
  when: ansible_local.util.init.system is defined and not tomcat_force_sysvinit
  include_vars: "service/{{ ansible_local.util.init.system }}.yml"

- name: Forcing SysVinit service management
  tags: tomcat
  when: ansible_local.util.init.system is defined and tomcat_force_sysvinit
  include_vars: "service/sysvinit.yml"

- name: Include assets persistency tasks
  tags: tomcat
  include: "{{ tomcat_path_to_lib_role }}/silpion.lib/tasks/datapersistency.yml"
  vars:
    include_tags: tomcat

- name: Include lib get_url
  tags: tomcat
  when: tomcat_fact_is_not_initial_check_mode
  include: "{{ tomcat_path_to_lib_role }}/silpion.lib/tasks/get_url.yml"
  vars:
    url: "{{ tomcat_download_url }}"
    filename: "{{ tomcat_redis_filename }}"
    checksum: "{{ tomcat_redis_checksum }}"

- name: Include lib copy
  tags: tomcat
  when: tomcat_fact_is_not_initial_check_mode
  include: "{{ tomcat_path_to_lib_role }}/silpion.lib/tasks/copy.yml"
  vars:
    filename: "{{ tomcat_redis_filename }}"


- name: Create Tomcat group(s)
  tags: tomcat
  become: true
  with_items: "{{ tomcat_instances }}"
  group:
    state: present
    name: "{{ item.group|default(tomcat_default_user_group) }}"

- name: Create Tomcat user(s)
  tags: tomcat
  become: true
  with_items: "{{ tomcat_instances }}"
  user:
    state: present
    name: "{{ item.user|default(tomcat_default_user_name) }}"
    home: "{{ item.home|default(tomcat_default_user_home) }}"
    group: "{{ item.group|default(tomcat_default_user_group) }}"
    system: "{{ item.system|default(tomcat_default_user_system) }}"
    createhome: true
    #comment: "Tomcat service user"

- name: Install catalina home directory
  tags: tomcat
  become: true
  file:
    state: directory
    dest: "{{ tomcat_env_catalina_home }}"
    owner: 0
    group: 0
    mode: 0755

- name: Extract Tomcat installation files to catalina home
  tags: tomcat
  become: true
  unarchive:
    src: "{{ lib_persistent_data_path_remote }}/{{ tomcat_redis_filename }}"
    dest: "{{ tomcat_env_catalina_home }}"
    extra_opts: ['--strip-components=1']
    remote_src: true
    owner: "{{ tomcat_default_user_name }}"
    group: "{{ tomcat_default_user_group }}"
    creates: "{{ tomcat_env_catalina_home }}/lib"

# FIXME: conf dir is symlink to /etc/tomcat9
- name: Install instance directories
  tags: tomcat
  become: true
  ignore_errors: yes
  with_nested:
    - "{{ tomcat_instances }}"
    - "{{ tomcat_instance_dirs }}"
  file:
    state: directory
    dest: "{{ item.0.path|default(tomcat_default_instance_path) }}/{{ item.0.name }}/{{ item.1 }}"
    owner: "{{ item.0.user|default(tomcat_default_user_name) }}"
    group: "{{ item.0.group|default(tomcat_default_user_group) }}"
    mode: 0755

- name: Register static/unmanaged conf files
  tags: tomcat
  register: tomcat_registered_conf_files
  check_mode: no
  changed_when: false
  when: tomcat_fact_is_not_initial_check_mode
#  failed_when: "{{ false if lib_fact_check_mode else omit }}"
  command: ls
      -1
      --ignore=web.xml
      --ignore=server.xml
      {{ tomcat_env_catalina_home }}/conf

- name: Install static/unmanaged conf files
  tags: tomcat
  become: true
  with_nested:
    - "{{ tomcat_instances }}"
    - "{{ (tomcat_registered_conf_files|default({})).stdout_lines|default([]) }}"
  when: tomcat_fact_is_not_initial_check_mode
  command: install
      --owner {{ item.0.user|default(tomcat_default_user_name) }}
      --group {{ item.0.group|default(tomcat_default_user_group) }}
      --mode 0640
      {{ tomcat_env_catalina_home }}/conf/{{ item.1 }}
      {{ item.0.path|default(tomcat_default_instance_path) }}/{{ item.0.name }}/conf/{{ item.1 }}
  args:
    creates: "{{ item.0.path|default(tomcat_default_instance_path) }}/{{ item.0.name }}/conf/{{ item.1 }}"

- name: Install instance server.xml
  tags: tomcat
  become: true
  with_items: "{{ tomcat_instances }}"
  register: tomcat_registered_install_server_xml
  template:
    src: "{{ item.server_xml_template|default(tomcat_default_server_xml_template) }}"
    dest: "{{ item.path|default(tomcat_default_instance_path) }}/{{ item.name }}/conf/server.xml"
    owner: "{{ item.user|default(tomcat_default_user_name) }}"
    group: "{{ item.group|default(tomcat_default_user_group) }}"
    mode: 0640

- name: Install instance web.xml
  tags: tomcat
  become: true
  with_items: "{{ tomcat_instances }}"
  register: tomcat_registered_install_web_xml
  template:
    src: "{{ item.web_xml_template|default(tomcat_default_web_xml_template) }}"
    dest: "{{ item.path|default(tomcat_default_instance_path) }}/{{ item.name }}/conf/web.xml"
    owner: "{{ item.user|default(tomcat_default_user_name) }}"
    group: "{{ item.group|default(tomcat_default_user_group) }}"
    mode: 0640

- name: Install instance logback.xml
  tags: tomcat
  become: true
  with_items: "{{ tomcat_instances }}"
  register: tomcat_registered_install_logback_xml
  template:
    src: "{{ item.logback_xml_template|default(tomcat_default_logback_xml_template) }}"
    dest: "{{ item.path|default(tomcat_default_instance_path) }}/{{ item.name }}/conf/logback.xml"
    owner: "{{ item.user|default(tomcat_default_user_name) }}"
    group: "{{ item.group|default(tomcat_default_user_group) }}"
    mode: 0640

- name: Install instance context.xml
  tags: tomcat
  become: true
  with_items: "{{ tomcat_instances }}"
  register: tomcat_registered_install_context_xml
  template:
    src: "{{ item.context_xml_template|default(tomcat_default_context_xml_template) }}"
    dest: "{{ item.path|default(tomcat_default_instance_path) }}/{{ item.name }}/conf/context.xml"
    owner: "{{ item.user|default(tomcat_default_user_name) }}"
    group: "{{ item.group|default(tomcat_default_user_group) }}"
    mode: 0640

- name: Install instance jmxremote.password
  tags: tomcat
  become: true
  with_items: "{{ tomcat_instances }}"
  when: item.jmxremote is defined 
  register: tomcat_registered_install_jmxremote_password
  template:
    src: "{{ item.jmxremote_password_template|default(tomcat_default_jmxremote_password_template) }}"
    dest: "{{ item.path|default(tomcat_default_instance_path) }}/{{ item.name }}/conf/jmxremote.password"
    owner: "{{ item.user|default(tomcat_default_user_name) }}"
    group: "{{ item.group|default(tomcat_default_user_group) }}"
    mode: 0400

- name: Install instance jmxremote.access
  tags: tomcat
  become: true
  with_items: "{{ tomcat_instances }}"
  when: item.jmxremote is defined
  register: tomcat_registered_install_jmxremote_access
  template:
    src: "{{ item.jmxremote_access_template|default(tomcat_default_jmxremote_access_template) }}"
    dest: "{{ item.path|default(tomcat_default_instance_path) }}/{{ item.name }}/conf/jmxremote.access"
    owner: "{{ item.user|default(tomcat_default_user_name) }}"
    group: "{{ item.group|default(tomcat_default_user_group) }}"
    mode: 0640

#   systemd requires to use separate environment files per instance
- name: Install instance systemd environment files
  tags: tomcat
  become: true
  when:
    - ansible_local.util.init.system is defined
    - ansible_local.util.init.system == 'systemd'
    - not tomcat_force_sysvinit
  with_items: "{{ tomcat_instances }}"
  register: tomcat_registered_install_instance_environment_files
  template:
    # FIXME: where to put config file
    #src: "{{ item.envfile_template|default(tomcat_default_envfile_template) }}"
    #dest: "{{ tomcat_sysconfig_dir }}/{{ item.name }}"
    src: "service_systemd_envfile.j2"
    dest: "{{ item.path|default(tomcat_default_instance_path) }}/{{ item.name }}/.systemd.conf"
    owner: "{{ item.user|default(tomcat_default_user_name) }}"
    group: "{{ item.group|default(tomcat_default_user_group) }}"
    mode: 0644

#   sysvinit environment files
- name: Install instance sysvinit environment files
  tags: tomcat
  become: true
  when:
    - ansible_local.util.init.system is defined
    - ansible_local.util.init.system == 'sysvinit'or tomcat_force_sysvinit
  with_items: "{{ tomcat_instances }}"
  register: tomcat_registered_install_instance_environment_files
  template:
    src: "{{ item.envfile_template|default(tomcat_default_envfile_template) }}"
    dest: "{{ tomcat_sysconfig_dir }}/{{ item.name }}"
    owner: "{{ item.user|default(tomcat_default_user_name) }}"
    group: "{{ item.group|default(tomcat_default_user_group) }}"
    mode: 0644

- name: Stop tomcat services
  tags: tomcat
  become: true
  when: tomcat_fact_upgrade_installation is defined and tomcat_fact_upgrade_installation
  with_items: "{{ tomcat_instances }}"
  service:
    state: stopped
    name: "{{ item.service_name|default(tomcat_default_service_name) }}"

#   install a service file for tomcat
#     systemd by default uses a templated service (one unit, many instances)
- name: Install tomcat services
  tags: tomcat
  become: true
  with_items: "{{ tomcat_instances }}"
  register: tomcat_registered_install_tomcat_service
  when: tomcat_fact_is_not_initial_check_mode
  template:
    src: "{{ item.service_template|default(tomcat_default_service_template) }}"
    dest: "{{ tomcat_service_dir }}/{{ item.service_file|default(tomcat_default_service_file) }}"
    owner: 0
    group: 0
    mode: "{{ tomcat_service_file_mode }}"

#   reload systemd if service file(s) have changed
#     suppress warnings from systemd
- name: Reload systemd
  tags: tomcat
  when:
    - tomcat_registered_install_tomcat_service.changed
    - ansible_local.util.init.system is defined
    - ansible_local.util.init.system == 'systemd'
    - not tomcat_force_sysvinit
  become: true
  failed_when: false
  changed_when: false
  command: systemctl daemon-reload

- name: Copy default config files to system `etc' directory
  tags: tomcat
  command: creates=/etc/tomcat{{ tomcat_version_major }} cp -apr {{ tomcat_env_catalina_home }}/conf /etc/tomcat{{ tomcat_version_major }}

- name: Set up permissions for system config directory
  tags: tomcat
  file: 
    dest: "/etc/tomcat{{ tomcat_version_major }}"
    owner: "{{ tomcat_default_user_name }}"
    group: "{{ tomcat_default_user_group }}"
    mode: u=rwX,g=rwX,o=rX
    recurse: no

- name: Move config files for instances into /etc/tomcat{{ tomcat_version_major }} system directory
  tags: tomcat
  with_items: "{{ tomcat_instances }}"
  command: creates=/etc/tomcat{{ tomcat_version_major }}/{{ item.name }} mv {{ item.path|default(tomcat_default_instance_path) }}/{{ item.name }}/conf /etc/tomcat{{ tomcat_version_major }}/{{ item.name }}

- name: Create symlink in CATALINA_BASE for instances
  tags: tomcat
  with_items: "{{ tomcat_instances }}"
  file:
    src: "/etc/tomcat{{ tomcat_version_major }}/{{ item.name }}"
    dest: "{{ item.path|default(tomcat_default_instance_path) }}/{{ item.name }}/conf"
    state: link

- name: Ensure tomcat service(s)
  tags: tomcat
  become: true
  with_items: "{{ tomcat_instances }}"
  when: tomcat_fact_is_not_initial_check_mode
  service:
    state: started
    enabled: true
    name: "{{ item.service_name|default(tomcat_default_service_name) }}"


#   Beware: Magic here
#     First of: register all instances which might have a changed event in various tasks
#       - instance configuration might have changed (server.xml)
#       - environment files for systemd might have changed
#       - service files might have changed
#     Result here is a dictionary containing the result of set_fact in a loop.
#       Each fact is stored at
#       - tomcat_registered_instances_requiring_restart.results.INDEX.ansible_facts.tomcat_fact_requires_restart_item
#       Values are one of
#       - tomcat service name in question (item.service_name) with sensible default
#       - None
- name: Register instances requiring restart
  tags: tomcat
  register: tomcat_registered_instances_requiring_restart
  with_items:
    - "{{ (tomcat_registered_install_server_xml|default({})).results|default({}) }}"
    - "{{ (tomcat_registered_install_web_xml|default({})).results|default({}) }}"
    - "{{ (tomcat_registered_install_logback_xml|default({})).results|default({}) }}"
    - "{{ (tomcat_registered_install_instance_environment_files|default({})).results|default({}) }}"
    - "{{ (tomcat_registered_install_tomcat_service|default({})).results|default({}) }}"
  when: tomcat_fact_is_not_initial_check_mode
  set_fact:
    tomcat_fact_requires_restart_item: "{{ item.item.service_name|default(tomcat_default_service_name) if item.item is defined and item.changed else 'None' }}"

#     This one maps all services in question from previous task into an iterable list
#       while stripping services named 'None'
- name: Configure instances requiring restart
  tags: tomcat
  when: tomcat_fact_is_not_initial_check_mode
  set_fact:
    tomcat_facts_requires_restart: "{{ tomcat_registered_instances_requiring_restart.results|map(attribute='ansible_facts.tomcat_fact_requires_restart_item')|list|unique|difference(['None']) }}"

#     We can now safely notify the service restart handler which in turn just loops
#       over all items in the resulting list 'tomcat_facts_requires_restart'.
- name: Trigger service handler
  tags: tomcat
  notify: service restart tomcat
  command: /bin/true

- name: Include local facts tasks
  tags: tomcat
  when: tomcat_fact_is_not_initial_check_mode
  include: "{{ tomcat_path_to_lib_role }}/silpion.lib/tasks/localfacts.yml"
  vars:
    namespace: tomcat
